dist: trusty
language: node_js
node_js: stable

script: yarn test:ci

jobs:
  include:
    - stage: npm release
      node_js: stable
      before_deploy:
      - yarn install
      - yarn build:ci
      deploy:
        skip_cleanup: true
        provider: npm
        email: "webdev@experium.ru"
        api_key: $NPM_API_KEY
        on:
          branch: master
    - stage: deploy gh pages
      before_deploy:
      - yarn install
      - yarn build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: "$GITHUB_TOKEN"
        keep-history: true
        local-dir: build
        on:
          branch: master
